---
azs:
- name: z1
  cloud_properties:
    availability_zone: {{ .AvailabilityZone }}

vm_types:
- name: concourse-web-small
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-medium
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-large
  cloud_properties:
    instance_type: t2.large
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-xlarge
  cloud_properties:
    instance_type: t2.xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-2xlarge
  cloud_properties:
    instance_type: t2.2xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-medium
  cloud_properties:
    instance_type: t2.medium {{ if .Spot }}
    spot_bid_price: 0.0567 # on-demand price: 0.0464
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-large
  cloud_properties: {{ if eq .WorkerType "m5" }} 
    instance_type: m5.large {{ if .Spot }}
    spot_bid_price: 0.13 # on-demand price: 0.107
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.large {{ if .Spot }}
    spot_bid_price: 0.13 # on-demand price: 0.111
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.xlarge {{ if .Spot }}
    spot_bid_price: 0.26 # on-demand price: 0.214
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.xlarge {{ if .Spot }}
    spot_bid_price: 0.27 # on-demand price: 0.222 
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-2xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.2xlarge {{ if .Spot }}
    spot_bid_price: 0.51 # on-demand price: 0.428
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.2xlarge {{ if .Spot }}
    spot_bid_price: 0.53 # on-demand price: 0.444
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-4xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.4xlarge {{ if .Spot }}
    spot_bid_price: 1.03 # on-demand price: 0.856
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.4xlarge {{ if .Spot }}
    spot_bid_price: 1.07 # on-demand price: 0.888
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-10xlarge
  cloud_properties:
    instance_type: m4.10xlarge {{ if .Spot }}
    spot_bid_price: 2.67 # on-demand price: 2.22
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-12xlarge
  cloud_properties:
    instance_type: m5.12xlarge {{ if .Spot }}
    spot_bid_price: 3.08 # on-demand price: 2.57
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-16xlarge
  cloud_properties:
    instance_type: m4.16xlarge {{ if .Spot }}
    spot_bid_price: 4.26 # on-demand price: 3.55
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-24xlarge
  cloud_properties:
    instance_type: m5.24xlarge {{ if .Spot }}
    spot_bid_price: 6.17 # on-demand price: 5.14
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: compilation
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.large {{ if .Spot }}
    spot_bid_price: 0.13 # on-demand price: 0.107
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.large {{ if .Spot }}
    spot_bid_price: 0.13 # on-demand price: 0.111
    spot_ondemand_fallback: true # {{ end }} {{ end }}

disk_types:
- name: default
  disk_size: 50_000
  cloud_properties:
    type: gp2
    encrypted: true
- name: large
  disk_size: 200_000
  cloud_properties:
    type: gp2
    encrypted: true

networks:
- name: public
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns:
    - 10.0.0.2
    az: z1
    static:
    - 10.0.0.6
    - 10.0.0.7
    reserved:
    - 10.0.0.1-10.0.0.5
    cloud_properties:
      subnet: {{ .PublicSubnetID }}
- name: private
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    dns:
    - 10.0.0.2
    az: z1
    reserved:
    - 10.0.1.1-10.0.1.5
    cloud_properties:
      subnet: {{ .PrivateSubnetID }}

- name: vip
  type: vip


vm_extensions:
- name: atc
  cloud_properties:
    security_groups:
    - {{ .VMsSecurityGroupID }}
    - {{ .ATCSecurityGroupID }}

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: private 