---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest
inputs:
- name: concourse-up
- name: binary-linux

run:
  path: concourse-up/ci/tasks/system-test-m5.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BINARY_PATH:
  VERBOSE:
